#!/bin/bash

gitlab-rails console production <<'EOF'
u = User.first

t = PersonalAccessToken.new({
    user: u,
    name: 'api',
    scopes: ['api']})
t.save!
File.write(
    '/tmp/gitlab-root-personal-access-token.txt',
    t.token)
EOF

